---
- name: Update dnf
  command:
    cmd: dnf update -y

- name: Upgrade dnf
  command:
    cmd: dnf upgrade -y

- name: Enable EPEL Repository
  dnf:
    name: epel-release
    state: latest
    update_cache: yes

- name: Install packages via dnf
  ansible.builtin.dnf:
    name:
    - python3-pip
    - nmap


