---
- name: Update dnf
  command:
    cmd: dnf update -y
  become: yes

- name: Upgrade dnf
  command:
    cmd: dnf upgrade -y
  become: yes

- name: Enable EPEL Repository
  dnf:
    name: epel-release
    state: latest
    update_cache: yes
  become: yes

- name: Install packages via dnf
  ansible.builtin.dnf:
    name: "{{ package_list }}"
  become: yes
