---
- name: Scan existing local orgs and repos
  include_tasks: find_local_orgs.yml

- name: Manage local clones of repos in 'managed_github_repos' list
  include_tasks: process_managed_github_repos_list.yml
  when: managed_github_repos is defined

- name: Manage directories for github orgs in 'managed_github_orgs' list
  include_tasks: process_managed_github_orgs_list.yml
  include_tasks: clone_all_repos_in_org.yml
  loop: "{{ managed_github_orgs }}"
  loop_control:
    loop_var: github_org
  when: managed_github_orgs is defined

