---
- name: Scan existing local orgs and repos
  include_tasks: local_scan/find_local_orgs.yml

- name: Manage local clones of repos in 'managed_github_repos' list
  include_tasks: process_managed_github_repos_list.yml
  when: managed_github_repos is defined

- name: Manage directories for github orgs in 'managed_github_orgs' list
  include_tasks: process_managed_github_orgs_list.yml
