---
- name: Manage each repo via github org and repo name
  include_tasks: status.yml
  loop: "{{ managed_github_repos }}"
  loop_control:
    loop_var: github
  vars:
    git_url: "{{ github.git_link }}"
    github_org: "{{ github.github_org }}"
    github_repo_name: "{{ github.github_repo_name }}"
    project_path: "{{ (github_repos_basedir, github_org, github_repo_name) | path_join }}"
  when: managed_github_repos is defined