---
- name: Upgrade pip
  pip:
    name: pip
    state: latest

- name: Install virtualenv via pip before creating venv
  pip:
    name: virtualenv
    executable: pip3

- name: Create venv
  pip:
    name: "{{ python_modules }}"
    state: present
    virtualenv: "~/managed_python39_venv"
    virtualenv_site_packages: no
    virtualenv_python: python3.9

