---
- name: Ensure Hashicorp repo is installed
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
  become: yes

- name: Ensure vault is installed
  ansible.builtin.package:
    name: vault
  become: yes
