---
- name: Prompt user for credential value
  pause:
    prompt: "{{ local_credential_filename }}?"
    echo: no
  register: local_credential_prompt

- name: Force write new credential value to credential file
  ansible.builtin.copy:
    content: "{{ credential_value | default('',true) }}"
    dest: "{{ local_credentials_full_path }}"
    mode: u+rwx,og-rwx
    force: yes
  vars:
    credential_value: "{{ local_credential_prompt.user_input }}"

- name: Credentials file stat after creation
  stat:
    path: "{{ local_credentials_full_path }}"
  register: credentials_stat