---
- name: Ensure directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ managed_credential_files_path }}"
    mode: u=rwx,g-rwx,o-rwx

- name: Credentials file stat {{ managed_credential_files_path }}
  stat:
    path: "{{ managed_credential_files_path }}"
  register: credentials_file

- name: Create empty credential file if one doesn't exist
  ansible.builtin.copy:
    content: ""
    dest: "{{ vault_credential_file_path }}"
    mode: u+rw,og-rwx
  when: credentials_file.stat.exists
  
- name: Ensure credential file has the correct permissions
  ansible.builtin.file:
    path: "{{ vault_credential_file_path }}"
    state: file
    mode: u=rw,g-rwx,o-rwx