---
- name: Add 1password key for yum repo
  rpm_key:
    state: present
    key: https://downloads.1password.com/linux/keys/1password.asc

- name: Register 1Password yum repo (which is used by dnf)
  ansible.builtin.yum_repository:
    name: 1Password Stable Channel
    description: 1Password Stable Channel
    file: 1password
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    gpgcheck: yes
    enabled: yes

- name: Install 1Password
  ansible.builtin.package:
    name: 1password
    state: present
    update_cache: yes
